version: "3.8"

services:
  # Web  server (Nginx)
  web:
    image: nginx
    volumes:
      - ./nginx/nginx.conf:/tmp/nginx.conf:ro
    environment:
      - FLASK_SERVER_ADDR=backend:9091
    command:
      /bin/bash -c "envsubst < /tmp/nginx.conf > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    ports:
      - "80:80"
    depends_on:
      - backend

  # Flask application
  backend:
    build:
      context: flask
      target: builder
    stop_signal: SIGINT
    environment:
      - FLASK_SERVER_PORT=9091
      - FLASK_MONGO_URI=mongodb://mongo:27017/keep_note
      ##- FLASK_MONGO_URI: mongodb://toothless:dragon@mongo:27017/keep_notes
    volumes:
      - ./flask:/src
    depends_on:
      - mongo

  # MongoDB database
  mongo:
    image: mongo
    restart: unless-stopped
    volumes:
      - ./volume/db:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=toothless
      - MONGO_INITDB_ROOT_PASSWORD=dragon
    

  # Mongo Express web interface
  mongo-express:
    image: mongo-express
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_ADMINUSERNAME=toothless
      - ME_CONFIG_MONGODB_ADMINPASSWORD=dragon
      # Optional security enhancements:
      - ME_CONFIG_BASIC_AUTH_USERNAME=express_user
      - ME_CONFIG_BASIC_AUTH_PASSWORD=dragon
    depends_on:
      - mongo

volumes:
  mongo-data:

